### PR TITLE
Milestone 5

### PR DESCRIPTION
**Pull request by NtwaliHeritier**
In this milestone, I added the calculator operations like:
- [x] addition
- [x] substraction
- [x] multiplication
- [x] division
- [x] modulus

### CODE REVIEW

**Review by Torres-ssf — CHANGES_REQUESTED** [review]
### Changes required :muscle: 
Hi @NtwaliHeritier :hand: 
Awesome job on this milestone so far :clap: 
But we need to fix some bugs before moving on.

- [ ] The `+/-` operand it's not working properly
err1

- [ ] After executing an operation, if you select another operator to do another calculation, the calculator does not behave properly
err2

- [ ] We should allow only one dot.
err3

- [ ] The modifier operator is not working right now. The expected behavior is `95 % == .95`
err4

- [ ] We need to update the README file by adding descriptive information about the project. Your README file has a good format right now, but it lacks information about this project. Let's add at least a description of what this project it's about. We also need to add at least one script that users can run to start you application.
Screenshot from 2021-02-03 13-37-02
Happy coding :computer: 
**Sergio Torres**

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes :recycle: :traffic_light: 
Hi @NtwaliHeritier, great job so far in implementing the comments outlined by the first TSE :+1: The following was resolved :100:  - The `+/-` operator - The issue with multiple `.` is resolved - The modifier operator is fixed :smile: Great job
However, there are a few comments we need to address before proceeding, kindly check the comments below:
- One of the comments from the first review is not addressed - "After executing an operation, if you select another operator to do another calculation, the calculator does not behave properly". Kindly address this comment
- Also let us improve our README file by adding instructions about how to clone and run the project locally :smile: 

Once these are fixed, kindly submit another code review request :+1: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Review by mikenath223 — CHANGES_REQUESTED** [review]
### Hi @NtwaliHeritier 👋

**Good job here. You've done quite well on this project. 👍**

However, let's make a couple of fixes.

- [ ] After clicking a number and then an operator, the number on the display immediately changes to zero. This shouldn't be the case; the number should still stay the same or better still the operator should be displayed beside the number. Kindly fix this.

### **STATUS: CHANGES REQUESTED** 👷‍♂️

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

**HAPPY CODING 🎉💻🎉**

**Michgolden Ukeje (CR)**

**Review by uche-inyama — APPROVED** [review]
## Approved

### Hi @NtwaliHeritier :wave: 

Good job implementing the changes, you can now move on with your next task.


### Have a great day :slightly_smiling_face: 


#### ``` Uchechukwu Henry Inyama ```

**Pull request merged**
